// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Todo {
    "id": number;
    "title": string;
    "completed": boolean;
}

export interface TodoStats {
    "total": number;
    "completed": number;
    "active": number;
}
