// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Add(title: string): $CancellablePromise<$models.Todo | null> {
    return $Call.ByID(368471028, title);
}

export function ClearCompleted(): $CancellablePromise<number> {
    return $Call.ByID(3284815095);
}

export function Delete(id: number): $CancellablePromise<void> {
    return $Call.ByID(1271921866, id);
}

export function GetAll(): $CancellablePromise<$models.Todo[] | null> {
    return $Call.ByID(851959634);
}

export function GetFiltered(filter: string): $CancellablePromise<$models.Todo[] | null> {
    return $Call.ByID(702393000, filter);
}

export function GetStats(): $CancellablePromise<$models.TodoStats> {
    return $Call.ByID(2561327386);
}

export function Toggle(id: number): $CancellablePromise<void> {
    return $Call.ByID(607591045, id);
}

export function Update(id: number, title: string): $CancellablePromise<void> {
    return $Call.ByID(203246836, id, title);
}
