// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * QRService handles QR Code generation
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Generate generates a QR code for the given text and size.
 */
export function Generate(text: string, size: number): $CancellablePromise<string | null> {
    return $Call.ByID(3609991677, text, size);
}

export function URL(text: string, size: number): $CancellablePromise<string> {
    return $Call.ByID(1044386931, text, size);
}
