// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Create(title: string, content: string): $CancellablePromise<$models.Note> {
    return $Call.ByID(3993631784, title, content);
}

export function Delete(id: string): $CancellablePromise<void> {
    return $Call.ByID(1433266871, id);
}

export function GetAll(): $CancellablePromise<$models.Note[] | null> {
    return $Call.ByID(3315001611);
}

export function LoadFromFile(): $CancellablePromise<void> {
    return $Call.ByID(4001022150);
}

export function SaveToFile(): $CancellablePromise<void> {
    return $Call.ByID(707959198);
}

export function Update(id: string, title: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(3863712317, id, title, content);
}
